### ISSUE TITLE
Copying Code Properly

### ISSUE THREAD

**Issue by mass1ve-err0r** [CuzImClicks/Clicks-Bot#13]
Hello you!
I’ve seen that you’ve starred one of my projects (GitHound) and just stripped the Cog and added it to your bot.

While I generally don’t have a problem with that, it’s appreciated if you’d at least credit where you find code & use it in your readme so others who stumble upon your repository can also see the sources.

**Comment by mass1ve-err0r** [comment]
On a sidenote, GitHound is licensed under GPL v3. Please also correct your repository to reflect the license terms.

**Comment by CuzImClicks** [comment]
Removed it

**Comment by mass1ve-err0r** [comment]
Sweet.
In case you have other copied code, do remember to comply and respect the license they ship with.

**Comment by CuzImClicks** [comment]
didn't know about the license thing had to read myself into it

**Comment by mass1ve-err0r** [comment]
All good, just good practice to respect copyright/ license terms instead of getting DMCA’d directly.

Just as general heads up, have fun coding!

**Comment by CuzImClicks** [comment]
thx for not doing that xD
